### Post "Hello!"
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Hello!"
}

### Post a command
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "/command"
}

### Get all the messages
GET http://localhost:8080/