CREATE TABLE IF NOT EXISTS messages
(
    id VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    text VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS commands
(
    id VARCHAR(60) PRIMARY KEY,
    command VARCHAR NOT NULL,
    description VARCHAR NOT NULL
);